version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
    - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: secret
    volumes:
      - ./dist:/var/www/html/wp-content/themes/customtheme
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: